### ISSUE TITLE
Fix deprecation warnings related to venv_activate in GH actions

### ISSUE THREAD

**Issue by ethanwhite** [weecology/neonwranglerpy#53]
We're getting warnings related to this line in our build:

https://github.com/weecology/neonwranglerpy/blob/d195613d853912eee086a9ddf18b0ea59bf21423/.github/workflows/python-package.yml#L22

Warning:

![Screenshot from 2023-03-28 08-05-47](https://user-images.githubusercontent.com/744427/228230721-4a365aa0-8f53-47b0-a376-3dd75e90525a.png)

**Comment by Pranav-Saxena** [comment]
I am taking up this issue as it has not been resolved till now

**Comment by Pranav-Saxena** [comment]
Hi, i saw the recent merge but still setup-python hasn't been upgraded to use the v4 tag and the current version of setup-python is v4. It will show deprecation warning unless upgraded to v4 tag!

**Comment by satsin06** [comment]
Yes, @Pranav-Saxena  you are correct about the latest version of setup-python which is v4, but it seems to me that the warning occurred because of `ld_libpath: ["export LD_LIBRARY_PATH=$(python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}"]` and in the current workflow there are no warnings.

**Comment by Pranav-Saxena** [comment]
@satsin06 This error is caused due to version issue only. you can find it mentioned here
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by satsin06** [comment]
Yes, @Pranav-Saxena I got you, I found the same [here](https://github.com/actions/setup-python/issues/578) but wasn't able to find any warning in the workflow. Your PR is having a merge conflict, please reset your branch with upstream/main. Although, I have opened a new PR regarding the same fix i.e., #66. Thanks for the suggestion

**Comment by Pranav-Saxena** [comment]
I have created a new PR #67 to fix the merge conflict!

**Comment by Pranav-Saxena** [comment]
@MarconiS yeah sure it's fine

**Comment by MarconiS** [comment]
Got it! Since it was already merged, I'll hold off merging #65
