### ISSUE TITLE
Clean up code formatting to flake8 standards

### ISSUE THREAD

**Issue by ethanwhite** [weecology/neonwranglerpy#54]
The tests are currently failing because we have a flake8 check running, but the code hasn't been fully cleaned up:

https://github.com/weecology/neonwranglerpy/actions/runs/4097816263/jobs/7066464655#step:6:371

Cleanup to code to flake8 standards and confirm that the tests now pass.

**Comment by satsin06** [comment]
Hey, @ethanwhite I am taking up this issue

**Comment by ethanwhite** [comment]
That is strange. It's hard to see what it is failing on. I'd probably try running the two associated checks locally and see if I could reproduce a failure with one of them:

https://github.com/weecology/neonwranglerpy/blob/d195613d853912eee086a9ddf18b0ea59bf21423/.github/workflows/python-package.yml#L44-L48

@henrykironde do you have any idea what's failing here?

**Comment by satsin06** [comment]
Try running `yapf -d --recursive ./neonwranglerpy --style=.style.yapf 2>&1` to reproduce the failure.

**Comment by satsin06** [comment]
> Hey, I have almost cleaned all the code but now I am facing another strange issue.
> 
> [https://github.com/satsin06/neonwranglerpy/actions/runs/4545923401/jobs/8013901555](url)
> 
> Please let me know, where I am wrong

@henrykironde Can you please help me with this issue?
