### ISSUE TITLE
Is rda2csv being used?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/neonwranglerpy#55]
The `rda2csv` function introduces an R dependency, which is definitely not ideal. I don't currently see it being used anywhere in the package. Am I missing something?

Here's a search for `rda`:

https://github.com/search?q=repo%3Aweecology%2Fneonwranglerpy%20rda&type=code

**Comment by satsin06** [comment]
Hey, @ethanwhite  Should I go ahead and fix the code and remove the dependency of R from the project? as I can see `rpy2` is only being used in the `rda2csv` function which is of no use as @Nageshbansal  told in the comment above.

**Comment by ethanwhite** [comment]
Thanks for the explanation @Nageshbansal and the PR @satsin06.

I've opened an issue in the source repo so see if they'll provide the files in a more compatible format:
https://github.com/NEONScience/NEON-utilities/issues/126

If they won't I think the easiest thing would probably be a GH Action either in this repo or a separate repo that downloads the file once a week or once a day, does the conversion, and pushes the updated version somewhere we can use it.

**Comment by Nageshbansal** [comment]
@MarconiS and I had a discussion regarding the files distribution with neon-data-API maintainers:

**Comment by ethanwhite** [comment]
Looks like they're going to add a version we can load directly in Python within the next week of so.

**Comment by ethanwhite** [comment]
The rda files are now available as csv files: https://github.com/NEONScience/NEON-utilities/tree/main/helper_files so we can move over to having the package download the most recent version when needed instead of converting and redistributing it ourselves.

Thanks to @cklunch for helping getting that setup for us over in https://github.com/NEONScience/NEON-utilities!

**Comment by MarconiS** [comment]
Thanks all for fixing this. We can close the issue.
