### ISSUE TITLE
Remove R from GH Actions testing

### ISSUE THREAD

**Issue by ethanwhite** [weecology/neonwranglerpy#59]
Once #57 is merged we should no longer need R in the build at all, so we should remove it from the GH actions build.

From a quick glance that looks like Lines 20, 31-34, removing the associated condition from 57, and maybe 23.

**Comment by satsin06** [comment]
I have opened a pull request regarding this issue, Please review it [#60](https://github.com/weecology/neonwranglerpy/pull/60)

**Comment by Pranav-Saxena** [comment]
Hi @ethanwhite I have opened a PR #61 fixing this issue. It's passing all the checks too. Can you please review it and merge it if it's fine!
